### ISSUE TITLE
项目报错

### ISSUE THREAD

**Issue by appbest** [F-loat/mpvue-packager#8]
> mpvue dev --mode h5

(node:13172) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `compile` of 'undefined' or 'null'.
    at addHooks (E:\SVN\mp\work\trunk\quick\node_modules\webpack-dev-server\lib\Server.js:131:49)
    at new Server (E:\SVN\mp\work\trunk\quick\node_modules\webpack-dev-server\lib\Server.js:144:5)
    at module.exports.require.then.webpackConfig (E:\SVN\mp\work\trunk\quick\node_modules\mpvue-packager-h5-plugin\dev.js:18:18)
    at internalTickCallback (internal/process/next_tick.js:77:7)
    at process._tickCallback (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:763:11)
    at startup (internal/bootstrap/node.js:308:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:878:3)
(node:13172) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13172) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by F-loat** [comment]
重新安装下依赖试试，有自定义什么配置没

**Comment by appbest** [comment]
没有，我加了 一个 iveiw

**Comment by appbest** [comment]
直接 按你的流程，执行也是报这个错误，没有其它

**Comment by F-loat** [comment]
我又没提供 h5 的模板。。你用 ithome 那个项目试试

**Comment by F-loat** [comment]
做线上项目的话建议你用 uniapp 吧

**Comment by F-loat** [comment]
把 webpack-dev-server 的版本降回去了
